# ==========================================
# Application
# ==========================================
spring.application.name=post-system

# ==========================================
# Server
# ==========================================
server.port=8080

# ==========================================
# PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/post_db
spring.datasource.username=postgres
spring.datasource.password=Neriume2
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect